
project_id = "nhlsrtubyvggtkyrhkuu"

[functions.create-checkout]
verify_jwt = true

[functions.manage-subscription]
verify_jwt = true

[functions.create-billing-portal]
verify_jwt = true

[functions.handle-subscription]
verify_jwt = false
