
project_id = "nhlsrtubyvggtkyrhkuu"

[functions.create-checkout]
verify_jwt = true

[functions.handle-subscription]
verify_jwt = false

[functions.manage-subscription]
verify_jwt = true

[functions.create-billing-portal]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = true

[functions.check-subscription-status]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false

[functions.send-session-reminder]
verify_jwt = false
