
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

interface TermsOfServiceModalProps {
  open: boolean;
  onClose: () => void;
}

export const TermsOfServiceModal = ({ open, onClose }: TermsOfServiceModalProps) => {
  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-3xl h-[80vh]">
        <DialogHeader>
          <DialogTitle className="text-2xl font-bold">Terms of Service</DialogTitle>
        </DialogHeader>
        <ScrollArea className="h-full pr-4">
          <div className="space-y-6 text-sm">
            <h2 className="text-xl font-semibold">Welcome to EduPortal</h2>
            
            <p>
              Welcome to EduPortal, operated by EduPortal, Inc ("EduPortal"). We provide educators, students, and educational institutions 
              with online access to educational tools and resources through our website and other services (collectively our "Services"). 
              Our Services are designed to enhance the learning experience and support student success.
            </p>
            
            <h3 className="text-lg font-medium mt-6">Your Rights to Use the Services</h3>
            <p>
              You may visit our website at any time, but to use our online Services you must be at least 13 years of age 
              and create an account providing your name, email, other requested information, and your selected password.
            </p>
            
            <p>
              If you are accessing or using the Services on behalf of an Educational Institution, you represent and warrant 
              that you have sufficient authority to enter into these Terms on behalf of your Educational Institution.
            </p>
            
            <p>
              Your account is for your personal use only, and you may not transfer your account to anyone else or permit 
              others to use your account. You are responsible for any activity or misuse associated with your account that 
              results from your failure to protect your password.
            </p>
            
            <p>
              By agreeing to these Terms and creating an account, EduPortal grants you a limited non-exclusive right to 
              access and use the Services we make available through your account, to be used only for educational purposes. 
              This right continues until either you or we terminate this agreement.
            </p>
            
            <h3 className="text-lg font-medium mt-6">Your Responsibilities When Using AI-Generated Content</h3>
            <p>
              Output created by our platform assists users, but does not replace your professional skills and judgment. 
              It is imperative that you review content generated by our Services and revise it to ensure it is appropriate for use.
            </p>
            
            <ul className="list-disc pl-8 space-y-2 my-4">
              <li>
                <strong>Review for accuracy:</strong> View AI-generated content as a starting point that requires your professional review and revisions.
              </li>
              <li>
                <strong>Check for bias and accuracy:</strong> AI can occasionally produce biased, fictitious, or incorrect content. Always double-check before sharing.
              </li>
              <li>
                <strong>Know the limits:</strong> Our AI engine's knowledge in terms of historical events may not include the most recent developments.
              </li>
              <li>
                <strong>Protect Privacy:</strong> Please do not include any personally identifiable information about students, parents, or others in information you provide to our Services.
              </li>
            </ul>
            
            <h3 className="text-lg font-medium mt-6">Prohibited Uses of the Services</h3>
            <p>You may not use the Services in a manner that:</p>
            
            <ul className="list-disc pl-8 space-y-2 my-4">
              <li>Infringes or violates the intellectual property rights or any other legal rights of any person</li>
              <li>Violates applicable law, regulations, or the policies of your organization</li>
              <li>Is harmful, fraudulent, deceptive, threatening, harassing, defamatory, obscene, or otherwise objectionable</li>
              <li>Jeopardizes the security of your account or anyone else's</li>
              <li>Attempts to obtain the password, account, or security information from any other user</li>
              <li>Threatens the security of any computer network, or cracks any passwords or security encryption codes</li>
              <li>Interferes with the proper working of the Services</li>
              <li>Decompiles, reverse engineers, or otherwise attempts to obtain the source code of the Services</li>
            </ul>
            
            <p>
              A violation of any of the foregoing is grounds for termination of your right to use or access the Services.
            </p>
            
            <h3 className="text-lg font-medium mt-6">Data Privacy Protection</h3>
            <p>
              EduPortal takes data privacy protection very seriously. For our current Privacy Policy, including a description of what information we collect, 
              how we use it, and your rights with respect to personally identifiable information we process, please refer to our Privacy Policy.
            </p>
            
            <h3 className="text-lg font-medium mt-6">Rights Regarding Use of Content You Provide</h3>
            <p>
              If you choose to post any messages or other content in areas of the Services that are designed for public display or communication with other users, 
              you are responsible for ensuring that you own or otherwise have the rights to post such material.
            </p>
            
            <p>
              By posting such material, you grant us a right that will survive any termination of these Terms and your use of the Services 
              to continue to reproduce and use such material to improve our Services worldwide.
            </p>
            
            <h3 className="text-lg font-medium mt-6">Terminating Services</h3>
            <p>
              You may terminate use of the Services at any time by deleting your account from the Profile Settings pages. 
              We may terminate your use of the Services at any time with prior notice, or immediately without notice for a material breach of these Terms.
            </p>
            
            <h3 className="text-lg font-medium mt-6">Links to Third-Party Sites</h3>
            <p>
              The EduPortal website may contain links to other websites ("Linked Sites"). Please note that EduPortal has no control over 
              the content of these Linked Sites, and is not responsible for the content on Linked Sites.
            </p>
            
            <h3 className="text-lg font-medium mt-6">Warranty Disclaimer and Limitation of Liability</h3>
            <p>
              THE SERVICES AND CONTENT ARE PROVIDED BY EDUPORTAL ON AN "AS-IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, 
              EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, 
              FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
            </p>
            
            <p>
              TO THE FULLEST EXTENT ALLOWED BY APPLICABLE LAW, UNDER NO CIRCUMSTANCES SHALL EDUPORTAL BE LIABLE FOR ANY INDIRECT, 
              SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY KIND.
            </p>
            
            <h3 className="text-lg font-medium mt-6">Indemnification</h3>
            <p>
              You agree to indemnify and hold harmless EduPortal from and against any and all losses, costs, liabilities, 
              and expenses arising out of or related to your violation of these Terms.
            </p>
            
            <h3 className="text-lg font-medium mt-6">Governing Law</h3>
            <p>
              These Terms shall be governed by the laws of the State without regard to conflicts of laws provisions, 
              save for applicable federal law.
            </p>
            
            <p className="mt-8 text-center text-xs text-gray-500">
              Last updated: {new Date().toLocaleDateString()}
            </p>
          </div>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
};
