
import { Info } from "lucide-react";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { InteractiveTooltip } from "@/components/ui/interactive-tooltip";

export const QuizDisclaimerText = () => (
  <div className="flex items-start gap-1.5 text-gray-500 text-xs italic mt-4 max-w-[calc(100%-20px)]">
    <p>
      Disclaimer: The questions and answers generated by our AI are intended for educational purposes only. 
      While we strive for accuracy, AI-generated content may not always be perfect. Please verify information 
      independently and use critical thinking when interpreting results.
    </p>
    <InteractiveTooltip
      trigger={<Info className="h-4 w-4 shrink-0 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 cursor-pointer" />}
      content={
        <div className="max-w-xs">
          <p className="mb-2 font-semibold">About AI-Generated Content</p>
          <p>
            Our platform utilizes AI technology to generate quiz questions and answers.
            While we aim to provide accurate and helpful content, AI systems can sometimes
            produce errors or inaccuracies. We encourage users to verify information
            independently and consult trusted sources where necessary.
          </p>
        </div>
      }
    />
  </div>
);

export const QuizDisclaimer = () => {
  return (
    <footer className="mt-auto py-4 border-t border-gray-100 dark:border-gray-800">
      <QuizDisclaimerText />
    </footer>
  );
};
